//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineChallenge.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineChallenge.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 4
        ///H 3 cat beach sun
        ///V 2 selfie smile
        ///V 2 garden selfie
        ///H 2 garden cat
        /// ähnelt.
        /// </summary>
        internal static string a_example {
            get {
                return ResourceManager.GetString("a_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 80000
        ///H 21 tr5fv t99tm t5nnd tj4f twzgl t6zkl tcz3g tf5wv tv1h01 tv7zt t5xl1 th8wv tkp5g tb5p6 tzdr4 t111w tc2j5 t1c76 tsmcf t2hzq tbj57
        ///H 9 tpvh8 t7fgq t6p61 t5x7p twzsw tkw11 tlhlt tlvcq tns01
        ///H 15 tjj0r tk3r t5pgg tf36x tvwcg tn4hp t0r1w t62gs t4pp6 tlql4 t982j tcdv8 tl3l6 tbb6j t3rgg
        ///H 15 t4rt4 t48r2 t0h5n tbzhk t52xx tx895 tfv2 tb25z tfmns t919l t3xvq tbns8 tqmvs tc9r2 tvr51
        ///H 15 t5rbj t8z5v t46vk t9h9q t98wh tjbc t7w5h tfzzf tk99r thzc5 txk58 thh6z t7s67 t6qt9 td6tp
        ///H 21 t4b1g twpq5 txrsg ttj8k twc3z  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string b_lovely_landscapes {
            get {
                return ResourceManager.GetString("b_lovely_landscapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1000
        ///V 7 tw52 t17 tmz1 t1l t8b1 tg6 tjb1
        ///H 7 twt1 tzb1 trn t6c t81 tgr tc51
        ///V 8 t001 t201 t81 tg11 td7 t652 t4q tb6
        ///H 10 tms t0c t8b1 tl3 tg02 tqz1 twd1 tqp1 t351 t21
        ///H 12 t9q1 t2m1 tld1 tt tpb t6r1 t892 tsj1 trn t4t1 tv81 tz41
        ///H 12 t822 t882 ttc1 t51 t071 t771 tn3 tfg1 t7d1 t332 t3b1 tbn1
        ///V 10 tlb tj62 tr51 tpz1 t502 t9s t14 t9c1 trx t291
        ///H 8 tjp t2x1 t2m1 t5p1 tdm1 tk6 twg1 ttc
        ///V 14 tc61 tl51 t3t tk6 tlf t1 t561 tm9 t911 tdd1 tz9 tcd tr5 t76
        ///H 11 tcc ts12 t391 t471 tzw tqg td42 t3x t762 tj82 tr42
        ///V 13 thd [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string c_memorable_moments {
            get {
                return ResourceManager.GetString("c_memorable_moments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 90000
        ///H 16 tm2 tl2 td4 t6 t82 t52 t86 th5 t44 t47 ts2 tc5 tl5 tc4 tf1 tw3
        ///V 15 tz2 t56 t42 t47 th5 tx4 tp6 t52 tm2 tw3 tw6 t85 t82 tn6 t87
        ///H 4 t51 tc4 tb5 t61
        ///V 13 tq1 tv3 tx1 tn6 t86 tc1 tb7 t72 t52 tw3 tm5 tr5 th4
        ///H 13 t47 t53 tl5 t85 tn6 tw3 tq2 t32 th2 t8 tz6 t01 tw5
        ///V 15 t02 tr2 t52 tp6 th5 t37 ts2 tl5 tn3 t44 th4 tv2 tq1 tn6 td
        ///V 9 tq6 t8 tv4 tz t22 t05 tn6 th4 t87
        ///V 11 tx tp2 tq6 tc4 t37 tr5 tb7 tl5 t8 t52 th4
        ///V 5 tl tw3 tp t6 t53
        ///H 9 th6 tl5 t6 t37 t53 tp6 t02 ts2 t05
        ///V 12 tb5 t05 tv t02 t12 tm2 t87 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string d_pet_pictures {
            get {
                return ResourceManager.GetString("d_pet_pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 80000
        ///V 25 tg4 t12 tv2 t3b t8b tdh tmb tl9 t3h tdf tcd tjc tg7 tzh t9f t7j tkd t9d t63 t tx5 t8c t65 t98 tzc
        ///V 16 tqb t9f tt6 tl2 tbf t4b tr2 tff t6j tw6 t0j t17 t64 t63 tb8 td7
        ///V 28 tjc tv8 t02 thg t9 tcc t69 tcd tbh t01 t7 tk6 tx6 t08 tpf tvh tqh t3b tgf tn9 th1 t78 tcg t14 tx7 tqf tm4 tqc
        ///V 18 t5c tg4 tk5 td3 t07 tc tb3 t36 tl8 twc th3 tkf td6 tw1 tph t9c t67 tb5
        ///V 10 t4b t03 tzg t45 tgj tqf t06 t77 tkb tf6
        ///V 24 tt1 t52 tv1 tdf txb tzh tkf t94 trf t21 t1f tn tf9 twb t95 t11 tt4 tx tlg t1 tpf tj txd t5d
        ///V [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string e_shiny_selfies {
            get {
                return ResourceManager.GetString("e_shiny_selfies", resourceCulture);
            }
        }
    }
}
