//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizza.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\data\\pizza\\c_medium.in")]
        public string UrlPizza {
            get {
                return ((string)(this["UrlPizza"]));
            }
            set {
                this["UrlPizza"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\data\\pizza\\c_medium.out")]
        public string UrlResult {
            get {
                return ((string)(this["UrlResult"]));
            }
            set {
                this["UrlResult"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReversePossibleShapes {
            get {
                return ((bool)(this["ReversePossibleShapes"]));
            }
            set {
                this["ReversePossibleShapes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckNeighbour {
            get {
                return ((bool)(this["CheckNeighbour"]));
            }
            set {
                this["CheckNeighbour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CutDistinctSlices {
            get {
                return ((bool)(this["CutDistinctSlices"]));
            }
            set {
                this["CutDistinctSlices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\data\\pizza\\pizza.png")]
        public string UrlPizzaImg {
            get {
                return ((string)(this["UrlPizzaImg"]));
            }
            set {
                this["UrlPizzaImg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\data\\pizza\\slicedPizza.png")]
        public string UrlSlicedPizzaImg {
            get {
                return ((string)(this["UrlSlicedPizzaImg"]));
            }
            set {
                this["UrlSlicedPizzaImg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\data\\pizza")]
        public string UrlDataDirectory {
            get {
                return ((string)(this["UrlDataDirectory"]));
            }
            set {
                this["UrlDataDirectory"] = value;
            }
        }
    }
}
